proxy:
  enable: false
  http_url: http://172.31.112.1:7890
  https_url: http://172.31.112.1:7890

dependencies:
  java: /root/.sdkman/candidates/java/current/bin/java
  scala: /root/.sdkman/candidates/scala/current/bin/scala
  sbt: /root/.sdkman/candidates/sbt/current/bin/sbt
  node: /usr/bin/node
  tree-sitter: /usr/bin/tree-sitter
  github-linguist: /usr/local/bin/github-linguist

log_level:
  INFO # [DEBUG, INFO, WARNING, ERROR]